// Azure Monitor Workspace (Managed Prometheus) + optional Azure Managed Grafana.
targetScope = 'resourceGroup'

@description('Azure region.')
param location string

@description('Azure Monitor Workspace (Prometheus) name.')
param azureMonitorWorkspaceName string

@description('Create an Azure Managed Grafana instance.')
param enableManagedGrafana bool = false

@description('Managed Grafana name (must be globally unique).')
param managedGrafanaName string = ''

@description('Resource tags.')
param tags object = {}

resource amw 'Microsoft.Monitor/accounts@2023-04-03' = {
  name: azureMonitorWorkspaceName
  location: location
  tags: tags
  properties: {}
}

resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = if (enableManagedGrafana) {
  name: empty(managedGrafanaName) ? 'amg-${uniqueString(resourceGroup().id)}' : managedGrafanaName
  location: location
  tags: tags
  sku: { name: 'Standard' }
  identity: { type: 'SystemAssigned' }
  properties: {
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    publicNetworkAccess: 'Enabled'
    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: [
        { azureMonitorWorkspaceResourceId: amw.id }
      ]
    }
  }
}

output azureMonitorWorkspaceId string = amw.id
output managedGrafanaId string = enableManagedGrafana ? grafana!.id : ''
output managedGrafanaPrincipalId string = enableManagedGrafana ? grafana!.identity.principalId : ''
